# Generated by Django 5.1.4 on 2025-01-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_remove_question_text_question_answer_1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Question1',
        ),
    ]
